### ISSUE TITLE
Make the theme support jupyter notebook

### ISSUE THREAD

**Issue by bobjason2020** [codigrate/jetbrains-themes#1]
When reading ipynb files using pycharm or dataspell software, the background of the page does not change color. I hope the notebook's code box and background color are different, which will help us to write code with jupyternotebook.
Or make a jupyter notebook style theme.
I would appreciate it if you could take my advice.

**Comment by furknyavuz** [comment]
Hi @bobjason2020,

Can you share a screenshot of the issue? It may help us to reproduce and fix it.

Thanks!

**Comment by bobjason2020** [comment]
![image](https://github.com/codigrate/jetbrains-themes/assets/148544047/aa0091cb-4e56-4953-86d5-d5cacf89e08e)
（For ipynb files）In the picture, When I use the Sakura Theme, the first part is pink, but the second part is white.I wish the second part would be pink as well, so that the dividing line between parts 2 and 3 would be clearer. The third part is the code block, and I think the different colors of the second part and the third part will help us improve the code editing experience.

**Comment by furknyavuz** [comment]
![Screenshot 2023-10-25 at 17 29 03](https://github.com/codigrate/jetbrains-themes/assets/2248168/4ad01133-006a-423d-807b-a4b24ae1364f)

Hi @bobjason2020,

I would completely agree with you on your valid request. Changing the background color of the second section to pink makes so much sense. However, the **code background** for **all other file types** will also become pink, which could be an unpleasant experience for many users.

Until JetBrains adds a separate field for the second section of .ipynb file types, I wanted to share a solution with you:

If you are using .ipynb files heavily, feel free to update the "Default text" background color to the color you wish. Just do not forget that if you are coding in other file types they will have pink background too.

**Comment by furknyavuz** [comment]
I'm closing the issue as answered.
