### ISSUE TITLE
Minor issue with the "Autumn" theme

### ISSUE THREAD

**Issue by IUSR** [codigrate/jetbrains-themes#2]
I've really enjoyed the "Autumn" theme, thank you so much for creating it!
A minor issue is that, when the current line is highlighted and there is no error, the background color is very close to the yellow light bulb icon of the context action menu. Please see attached screenshot. Is this intended? Because if there's an error, then the light bulb icon will be red and easily distinguishable.
![image](https://github.com/codigrate/jetbrains-themes/assets/42600/5e49a977-c7f7-4498-90ce-0571031c4b42)

**Comment by furknyavuz** [comment]
Thank you so much for your kind words! We're delighted to hear that you enjoy the theme. 🍁

If you want, you can try our other themes too! Here is the link:
https://plugins.jetbrains.com/organizations/Codigrate

Also, if you please you can write a review and rate us which is so valuable to us.
https://plugins.jetbrains.com/plugin/22700-autumn-theme

----------------------------------------------------------------------------------

We will have a look into that issue, and possibly made the color difference more distinguishable.
Thank you for your patience while waiting.

Have a nice day.

**Comment by IUSR** [comment]
I did just that👍 I totally stumbled upon this theme and I hope more people can try it; there's been hardly anything new since solarized, dracula, monokai, nord. I've installed all your other themes, too, but I routinely use Autumn and Aurora Borealis. I hope more people can discover and enjoy your designs!

**Comment by furknyavuz** [comment]
The color change will be effective with the new release.
Thank you for your 5 star review!

-----------------------------------------------------------------------------------------------------

There is a minor IntelliJ bug that you may face while updating the theme.
So, to not have that issue, please follow the steps below:

1. If you are using the theme that you want to update, select another theme first.
2. Then update the theme.
3. Restart the ide.
4. Finally, switch it back to the theme that you updated.

**Comment by IUSR** [comment]
Thanks for the prompt fix!
