### ISSUE TITLE
Extension request to VS Code?

### ISSUE THREAD

**Issue by mertkaraoglu** [codigrate/jetbrains-themes#4]
Many thanks for these gorgeous themes, would you consider extending them to VS Code?

**Comment by furknyavuz** [comment]
Hi @mertkaraoglu,
Thank you so much for your kind words! We're delighted to hear that you enjoy the themes.

Yes, it is on our future plans. Right now, we are focusing on Jetbrains products.
Thank you for showing your support and sharing your idea with us!

----------------------------

If you would like to show further support to us, feel free to share your review to your favorite theme! 👍

https://plugins.jetbrains.com/organizations/Codigrate

Thank you!
